import { Questrial, Rubik } from 'next/font/google';
import "./globals.css";
import Navbar from '@/components/shared/Navbar';

const rubik = Rubik({
  subsets: ['latin'],
  weight: ['400', '500', '700'], 
  display: 'swap',
});

const questrial = Questrial({
  subsets: ['latin'],
  weight: '400',
  display: 'swap',
  variable: '--font-questrial',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
       className={`${rubik.variable} ${questrial.variable}`}
      >
        <Navbar></Navbar>
        {children}
      </body>
    </html>
  );
}
